import 'dice.dart';

drawCalling() => drawFrom(_callings);

drawDestiny() => drawFrom(_destinies);

drawFate() => drawFrom(_fates);

const _callings = [
  "Adventure and excitement",
  "Mastery of the arcane",
  "Oneness with spirit",
  "Protection of nature",
  "Temporal power",
  "Spiritual or religious power",
  "TRUE love",
  "Mastery of the martial arts",
  "Physical perfection",
  "Transmission of knowledge",
  "Wealth",
  "Justice",
  "Inner peace",
  "Creating change",
  "Mediation of extremes",
  "Trickery or uncovering the same",
  "Lowering the lofty",
  "Artistic mastery",
  "Discovering and learning secrets",
  "Championing the everyday",
  "Atonement",
  "Exploration and discovery",
];

const _destinies = [
  "Courageous",
  "Compromising",
  "Stalwart",
  "Calm",
  "Humble",
  "Optimistic",
  "Careful",
  "Free-spirited",
  "Compassionate",
  "Dispassionate",
  "Perceptive",
  "Bold",
  "Exacting",
  "Logical",
  "Emotional",
  "Affable",
  "Gregarious",
  "Ambitious",
  "Hopeful",
  "Reflective",
  "Practical",
  "Daring",
  "Carefree",
  "Joyful",
  "Expressive",
  "Charismatic",
  "Devoted",
  "Thoughtful",
  "Enthusiastic",
  "Conciliatory",
  "Industrious",
  "Merry",
  "Competitive",
  "Confident",
  "Adventurous",
  "Witty",
  "Diplomatic",
  "Moderate",
  "Hardworking",
  "Resolute",
  "Curious",
  "Honest",
  "Generous",
  "Judicious",
  "Meticulous",
  "Forward-thinking",
  "Hopeful",
  "Magnanimous",
  "Patient",
  "Dedicated",
  "Appreciative",
  "Open-minded",
  "Inquisitive",
  "Determined",
  "Nurturing",
  "Resourceful"
];

const _fates = [
  "Cowardly",
  "Indecisive",
  "Treacherous",
  "Agitated",
  "Cruel",
  "Pessimistic",
  "Careless",
  "Stagnant",
  "Despondent",
  "Cold",
  "Insensitive",
  "Boastful",
  "Petty",
  "Arbitrary",
  "Hysterical",
  "Standoffish",
  "Inhibited",
  "Apathetic",
  "Remorseful",
  "Excessively",
  "Deluded",
  "Stubborn",
  "Peevish",
  "Depressed",
  "Deceptive",
  "Manipulative",
  "Capricious",
  "Reactionary",
  "Overzealous",
  "Pugnacious",
  "Slothful",
  "Dour",
  "Complacent",
  "Apprehensive",
  "Reckless",
  "Sluggish",
  "Domineering",
  "Obsessive",
  "Idle",
  "Cynical",
  "Jaded",
  "Self-righteous",
  "Greedy",
  "Narrow-minded",
  "Sloppy",
  "Miserly",
  "Hopeless",
  "Envious",
  "Impatient",
  "Mercenary",
  "Fearful",
  "Intolerant",
  "Wasteful",
  "Hasty",
  "Suspicious",
  "Sneaky"
];
