language: dart
script: pub global activate webdev; webdev build -r --output=build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build/web
  verbose: true
  on:
    branch: master