name: blue_rose_character_creator
description: A web app for (randomly) generating Blue Rose character sheets
version: 0.0.1
homepage: https://github.com/emerssso/blue_rose_character_creator
author: Conner Kasten <conner.kasten@emerssso.com>

environment:
  sdk: '>=2.1.0'

dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  angular: ^5.1.0
  angular_components: ^0.10.1
  angular_forms: ^2.1.0
  sass_builder: ^2.0.0

dev_dependencies:
  angular_test: ^2.1.0
  test: ^1.5.1+1
