name: blue_rose_character_creator
description: A web app for (randomly) generating Blue Rose character sheets
version: 0.0.1
homepage: https://github.com/emerssso/blue_rose_character_creator
author: Conner Kasten <conner.kasten@emerssso.com>

environment:
  sdk: '>=2.7.0'

dependencies:
  blue_rose_character:
    path: character
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_forms: ^2.1.2
  sass_builder: ^2.1.3

dev_dependencies:
  angular_test: ^2.1.0
  test: ^1.5.1+1
