List<String> callings = new List.unmodifiable(const [
  "Adventure and excitement",
  "Mastery of the arcane",
  "Oneness with spirit",
  "Protection of nature",
  "Temporal power",
  "Spiritual or religious power",
  "TRUE love",
  "Mastery of the martial arts",
  "Physical perfection",
  "Transmission of knowledge",
  "Wealth",
  "Justice",
  "Inner peace",
  "Creating change",
  "Mediation of extremes",
  "Trickery or uncovering the same",
  "Lowering the lofty",
  "Artistic mastery",
  "Discovering and learning secrets",
  "Championing the everyday",
  "Atonement",
  "Exploration and discovery",
]);

List<String> destinies = new List.unmodifiable(const[
  "Courageous",
  "Compromising",
  "Stalwart",
  "Calm",
  "Humble",
  "Optimistic",
  "Careful",
  "Free-spirited",
  "Compassionate",
  "Dispassionate",
  "Perceptive",
  "Bold",
  "Exacting",
  "Logical",
  "Emotional",
  "Affable",
  "Gregarious",
  "Ambitious",
  "Hopeful",
  "Reflective",
  "Practical",
  "Daring",
  "Carefree",
  "Joyful",
  "Expressive",
  "Charismatic",
  "Devoted",
  "Thoughtful",
  "Enthusiastic",
  "Conciliatory",
  "Industrious",
  "Merry",
  "Competitive",
  "Confident",
  "Adventurous",
  "Witty",
  "Diplomatic",
  "Moderate",
  "Hardworking",
  "Resolute",
  "Curious",
  "Honest",
  "Generous",
  "Judicious",
  "Meticulous",
  "Forward-thinking",
  "Hopeful",
  "Magnanimous",
  "Patient",
  "Dedicated",
  "Appreciative",
  "Open-minded",
  "Inquisitive",
  "Determined",
  "Nurturing",
  "Resourceful"
]);

List<String> fates = new List.unmodifiable(const [
  "Cowardly",
  "Indecisive",
  "Treacherous",
  "Agitated",
  "Cruel",
  "Pessimistic",
  "Careless",
  "Stagnant",
  "Despondent",
  "Cold",
  "Insensitive",
  "Boastful",
  "Petty",
  "Arbitrary",
  "Hysterical",
  "Standoffish",
  "Inhibited",
  "Apathetic",
  "Remorseful",
  "Excessively",
  "Deluded",
  "Stubborn",
  "Peevish",
  "Depressed",
  "Deceptive",
  "Manipulative",
  "Capricious",
  "Reactionary",
  "Overzealous",
  "Pugnacious",
  "Slothful",
  "Dour",
  "Complacent",
  "Apprehensive",
  "Reckless",
  "Sluggish",
  "Domineering",
  "Obsessive",
  "Idle",
  "Cynical",
  "Jaded",
  "Self-righteous",
  "Greedy",
  "Narrow-minded",
  "Sloppy",
  "Miserly",
  "Hopeless",
  "Envious",
  "Impatient",
  "Mercenary",
  "Fearful",
  "Intolerant",
  "Wasteful",
  "Hasty",
  "Suspicious",
  "Sneaky"
]);
