name: blue_rose_character
description: A shared library for generating Blue Rose characters
version: 0.0.1
homepage: https://github.com/emerssso/blue_rose_character_creator
author: Conner Kasten <conner.kasten@emerssso.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.14.3